import { S3File } from "./components/types";

// Mock S3 bucket data for testing the UI
export const MOCK_FILES: Record<string, S3File[]> = {
  // Root level files and folders
  "": [
    {
      id: "folder-1",
      name: "images",
      size: "-",
      lastModified: "2026-01-10T14:30:00Z",
      type: "folder",
      path: "images/",
      key: "images/",
      isFolder: true,
    },
    {
      id: "folder-2",
      name: "documents",
      size: "-",
      lastModified: "2026-01-08T09:15:00Z",
      type: "folder",
      path: "documents/",
      key: "documents/",
      isFolder: true,
    },
    {
      id: "folder-3",
      name: "videos",
      size: "-",
      lastModified: "2026-01-05T16:45:00Z",
      type: "folder",
      path: "videos/",
      key: "videos/",
      isFolder: true,
    },
    {
      id: "folder-4",
      name: "backups",
      size: "-",
      lastModified: "2026-01-12T11:20:00Z",
      type: "folder",
      path: "backups/",
      key: "backups/",
      isFolder: true,
    },
    {
      id: "file-1",
      name: "readme.md",
      size: "2.5 KB",
      lastModified: "2026-01-13T08:00:00Z",
      type: "document",
      path: "readme.md",
      key: "readme.md",
      url: "https://picsum.photos/seed/readme/200",
      isFolder: false,
    },
    {
      id: "file-2",
      name: "config.json",
      size: "1.2 KB",
      lastModified: "2026-01-11T17:30:00Z",
      type: "document",
      path: "config.json",
      key: "config.json",
      url: "https://picsum.photos/seed/config/200",
      isFolder: false,
    },
    {
      id: "file-3",
      name: "logo.png",
      size: "45.8 KB",
      lastModified: "2026-01-09T12:00:00Z",
      type: "image",
      path: "logo.png",
      key: "logo.png",
      url: "https://picsum.photos/seed/logo/400/300",
      isFolder: false,
    },
  ],

  // Images folder
  images: [
    {
      id: "folder-img-1",
      name: "screenshots",
      size: "-",
      lastModified: "2026-01-10T10:00:00Z",
      type: "folder",
      path: "images/screenshots/",
      key: "images/screenshots/",
      isFolder: true,
    },
    {
      id: "folder-img-2",
      name: "avatars",
      size: "-",
      lastModified: "2026-01-09T15:30:00Z",
      type: "folder",
      path: "images/avatars/",
      key: "images/avatars/",
      isFolder: true,
    },
    {
      id: "img-1",
      name: "hero-banner.jpg",
      size: "1.2 MB",
      lastModified: "2026-01-10T14:30:00Z",
      type: "image",
      path: "images/hero-banner.jpg",
      key: "images/hero-banner.jpg",
      url: "https://picsum.photos/seed/hero/800/400",
      isFolder: false,
    },
    {
      id: "img-2",
      name: "background.png",
      size: "856 KB",
      lastModified: "2026-01-10T13:45:00Z",
      type: "image",
      path: "images/background.png",
      key: "images/background.png",
      url: "https://picsum.photos/seed/bg/600/400",
      isFolder: false,
    },
    {
      id: "img-3",
      name: "icon-set.svg",
      size: "24 KB",
      lastModified: "2026-01-08T09:00:00Z",
      type: "image",
      path: "images/icon-set.svg",
      key: "images/icon-set.svg",
      url: "https://picsum.photos/seed/icons/200/200",
      isFolder: false,
    },
    {
      id: "img-4",
      name: "product-photo.webp",
      size: "542 KB",
      lastModified: "2026-01-07T16:20:00Z",
      type: "image",
      path: "images/product-photo.webp",
      key: "images/product-photo.webp",
      url: "https://picsum.photos/seed/product/500/500",
      isFolder: false,
    },
  ],

  // Images/screenshots subfolder
  "images/screenshots": [
    {
      id: "ss-1",
      name: "dashboard-v1.png",
      size: "2.1 MB",
      lastModified: "2026-01-10T10:15:00Z",
      type: "image",
      path: "images/screenshots/dashboard-v1.png",
      key: "images/screenshots/dashboard-v1.png",
      url: "https://picsum.photos/seed/dash1/1200/800",
      isFolder: false,
    },
    {
      id: "ss-2",
      name: "dashboard-v2.png",
      size: "2.3 MB",
      lastModified: "2026-01-10T10:30:00Z",
      type: "image",
      path: "images/screenshots/dashboard-v2.png",
      key: "images/screenshots/dashboard-v2.png",
      url: "https://picsum.photos/seed/dash2/1200/800",
      isFolder: false,
    },
    {
      id: "ss-3",
      name: "mobile-view.png",
      size: "890 KB",
      lastModified: "2026-01-09T14:00:00Z",
      type: "image",
      path: "images/screenshots/mobile-view.png",
      key: "images/screenshots/mobile-view.png",
      url: "https://picsum.photos/seed/mobile/400/800",
      isFolder: false,
    },
  ],

  // Images/avatars subfolder
  "images/avatars": [
    {
      id: "avatar-1",
      name: "user-default.png",
      size: "12 KB",
      lastModified: "2026-01-09T15:30:00Z",
      type: "image",
      path: "images/avatars/user-default.png",
      key: "images/avatars/user-default.png",
      url: "https://picsum.photos/seed/avatar1/150/150",
      isFolder: false,
    },
    {
      id: "avatar-2",
      name: "admin-avatar.jpg",
      size: "18 KB",
      lastModified: "2026-01-08T11:00:00Z",
      type: "image",
      path: "images/avatars/admin-avatar.jpg",
      key: "images/avatars/admin-avatar.jpg",
      url: "https://picsum.photos/seed/avatar2/150/150",
      isFolder: false,
    },
  ],

  // Documents folder
  documents: [
    {
      id: "folder-doc-1",
      name: "reports",
      size: "-",
      lastModified: "2026-01-07T10:00:00Z",
      type: "folder",
      path: "documents/reports/",
      key: "documents/reports/",
      isFolder: true,
    },
    {
      id: "doc-1",
      name: "user-guide.pdf",
      size: "3.4 MB",
      lastModified: "2026-01-08T09:15:00Z",
      type: "document",
      path: "documents/user-guide.pdf",
      key: "documents/user-guide.pdf",
      url: "#",
      isFolder: false,
    },
    {
      id: "doc-2",
      name: "api-documentation.pdf",
      size: "1.8 MB",
      lastModified: "2026-01-06T14:30:00Z",
      type: "document",
      path: "documents/api-documentation.pdf",
      key: "documents/api-documentation.pdf",
      url: "#",
      isFolder: false,
    },
    {
      id: "doc-3",
      name: "changelog.txt",
      size: "45 KB",
      lastModified: "2026-01-13T09:00:00Z",
      type: "document",
      path: "documents/changelog.txt",
      key: "documents/changelog.txt",
      url: "#",
      isFolder: false,
    },
    {
      id: "doc-4",
      name: "license.txt",
      size: "11 KB",
      lastModified: "2025-12-15T08:00:00Z",
      type: "document",
      path: "documents/license.txt",
      key: "documents/license.txt",
      url: "#",
      isFolder: false,
    },
  ],

  // Documents/reports subfolder
  "documents/reports": [
    {
      id: "report-1",
      name: "Q4-2025-report.xlsx",
      size: "456 KB",
      lastModified: "2026-01-07T10:00:00Z",
      type: "document",
      path: "documents/reports/Q4-2025-report.xlsx",
      key: "documents/reports/Q4-2025-report.xlsx",
      url: "#",
      isFolder: false,
    },
    {
      id: "report-2",
      name: "annual-summary.docx",
      size: "2.1 MB",
      lastModified: "2026-01-05T16:00:00Z",
      type: "document",
      path: "documents/reports/annual-summary.docx",
      key: "documents/reports/annual-summary.docx",
      url: "#",
      isFolder: false,
    },
  ],

  // Videos folder
  videos: [
    {
      id: "video-1",
      name: "intro-tutorial.mp4",
      size: "45.2 MB",
      lastModified: "2026-01-05T16:45:00Z",
      type: "video",
      path: "videos/intro-tutorial.mp4",
      key: "videos/intro-tutorial.mp4",
      url: "#",
      isFolder: false,
    },
    {
      id: "video-2",
      name: "product-demo.mov",
      size: "128 MB",
      lastModified: "2026-01-03T11:30:00Z",
      type: "video",
      path: "videos/product-demo.mov",
      key: "videos/product-demo.mov",
      url: "#",
      isFolder: false,
    },
    {
      id: "video-3",
      name: "webinar-recording.webm",
      size: "256 MB",
      lastModified: "2025-12-28T14:00:00Z",
      type: "video",
      path: "videos/webinar-recording.webm",
      key: "videos/webinar-recording.webm",
      url: "#",
      isFolder: false,
    },
  ],

  // Backups folder
  backups: [
    {
      id: "folder-backup-1",
      name: "2026-01",
      size: "-",
      lastModified: "2026-01-12T11:20:00Z",
      type: "folder",
      path: "backups/2026-01/",
      key: "backups/2026-01/",
      isFolder: true,
    },
    {
      id: "folder-backup-2",
      name: "2025-12",
      size: "-",
      lastModified: "2025-12-31T23:59:00Z",
      type: "folder",
      path: "backups/2025-12/",
      key: "backups/2025-12/",
      isFolder: true,
    },
    {
      id: "backup-1",
      name: "database-snapshot.sql.gz",
      size: "89 MB",
      lastModified: "2026-01-12T11:20:00Z",
      type: "archive",
      path: "backups/database-snapshot.sql.gz",
      key: "backups/database-snapshot.sql.gz",
      url: "#",
      isFolder: false,
    },
  ],

  // Backups/2026-01 subfolder
  "backups/2026-01": [
    {
      id: "backup-jan-1",
      name: "backup-2026-01-01.tar.gz",
      size: "1.2 GB",
      lastModified: "2026-01-01T00:05:00Z",
      type: "archive",
      path: "backups/2026-01/backup-2026-01-01.tar.gz",
      key: "backups/2026-01/backup-2026-01-01.tar.gz",
      url: "#",
      isFolder: false,
    },
    {
      id: "backup-jan-7",
      name: "backup-2026-01-07.tar.gz",
      size: "1.3 GB",
      lastModified: "2026-01-07T00:05:00Z",
      type: "archive",
      path: "backups/2026-01/backup-2026-01-07.tar.gz",
      key: "backups/2026-01/backup-2026-01-07.tar.gz",
      url: "#",
      isFolder: false,
    },
    {
      id: "backup-jan-14",
      name: "backup-2026-01-14.tar.gz",
      size: "1.4 GB",
      lastModified: "2026-01-14T00:05:00Z",
      type: "archive",
      path: "backups/2026-01/backup-2026-01-14.tar.gz",
      key: "backups/2026-01/backup-2026-01-14.tar.gz",
      url: "#",
      isFolder: false,
    },
  ],

  // Backups/2025-12 subfolder
  "backups/2025-12": [
    {
      id: "backup-dec-1",
      name: "backup-2025-12-01.tar.gz",
      size: "1.1 GB",
      lastModified: "2025-12-01T00:05:00Z",
      type: "archive",
      path: "backups/2025-12/backup-2025-12-01.tar.gz",
      key: "backups/2025-12/backup-2025-12-01.tar.gz",
      url: "#",
      isFolder: false,
    },
    {
      id: "backup-dec-15",
      name: "backup-2025-12-15.tar.gz",
      size: "1.15 GB",
      lastModified: "2025-12-15T00:05:00Z",
      type: "archive",
      path: "backups/2025-12/backup-2025-12-15.tar.gz",
      key: "backups/2025-12/backup-2025-12-15.tar.gz",
      url: "#",
      isFolder: false,
    },
    {
      id: "backup-dec-31",
      name: "backup-2025-12-31.tar.gz",
      size: "1.2 GB",
      lastModified: "2025-12-31T00:05:00Z",
      type: "archive",
      path: "backups/2025-12/backup-2025-12-31.tar.gz",
      key: "backups/2025-12/backup-2025-12-31.tar.gz",
      url: "#",
      isFolder: false,
    },
  ],
};

// Helper function to get mock files for a given path
export function getMockFiles(path: string): S3File[] {
  // Normalize path - remove trailing slash
  const normalizedPath = path.replace(/\/$/, "");
  return MOCK_FILES[normalizedPath] || [];
}

// Check if we should use mock data (for testing)
export const USE_MOCK_DATA = true;

// Demo bucket that will use mock data
export const DEMO_BUCKET_NAME = "demo-bucket";
